default_job = "run"

[jobs.run]
command = [
    "cargo", "leptos", "watch"
]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"

[jobs.test]
command = [
    "cargo", "nextest", "run",
    "--color", "always",
]
need_stdout = true
analyzer = "nextest"
