[package]
name = "blog"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.26"
gray_matter = "0.2.6"
include_dir = "0.7.3"
leptos = "0.3.1"
leptos_icons = { version = "0.0.14", features = [
itertools = "0.11.0"
    "macros",
    "AiGithubFilled",
    "AiMailFilled",
    "AiLinkedinFilled",
    "AiTwitterOutlined",
    "BiTelegram"
] }
leptos_router = { version = "0.3.1", features = ["hydrate"] }
pulldown-cmark = "0.9.3"
serde = "1.0.164"

# TODO optimize WASM binary size
# https://leptos-rs.github.io/leptos/appendix_binary_size.html
# [profile.release]
