[package]
name = "blog"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.12"
askama_axum = "0.4"
axum = "0.7"
include_dir = "0.7"
serde = { version = "1.0.210", features = ["derive"] }
tokio = { version = "1.40", features = ["macros", "rt-multi-thread", "signal"] }

[dev-dependencies]
http-body-util = "0.1"
tower = { version = "0.5", features = ["util"] }
