baseURL: https://khuedoan.com/
languageCode: en-us
title: Khue Doan

module:
  imports:
    path: "github.com/adityatelange/hugo-PaperMod"

params:
  env: production
  description: "Khue Doan's personal website"
  homeInfoParams:
    title: "Hi there, I'm Khue \U0001F44B"
    content: "Welcome to my website, where I write about Linux, DevOps, homelab, workflow optimization, and more!"
  socialIcons:
    - name: email
      url: "mailto:mail@khuedoan.com"
    - name: github
      url: "https://github.com/khuedoan"
    - name: linkedin
      url: "https://linkedin.com/in/khuedoan"
  showReadingTime: true
  showToc: true
  showCodeCopyButtons: true
  hideFooter: true

outputs:
  home:
    - HTML
    - JSON
    - RSS

menu:
  main:
    - name: Search
      url: /search/
      weight: 1
    - name: Archives
      url: /archives/
      weight: 2

enableEmoji: true
