baseURL: https://khuedoan.com/
languageCode: en-us
title: Khue Doan

theme: "github.com/adityatelange/hugo-PaperMod"

params:
  homeInfoParams:
    Title: "Hi, I'm Khue \U0001F44B"
    Content: More content coming soon!
  socialIcons:
    - name: email
      url: "mailto:mail@khuedoan.com"
    - name: github
      url: "https://github.com/khuedoan"
    - name: linkedin
      url: "https://linkedin.com/in/khuedoan"

menu:
  main:
    - name: about
      url: /about/
