baseURL: https://khuedoan.com/
languageCode: en-us
title: Khue Doan

module:
  imports:
    path: "github.com/adityatelange/hugo-PaperMod"

params:
  env: production
  homeInfoParams:
    title: "Hi there, I'm Khue \U0001F44B"
    content: More content coming soon!
  socialIcons:
    - name: email
      url: "mailto:mail@khuedoan.com"
    - name: github
      url: "https://github.com/khuedoan"
    - name: linkedin
      url: "https://linkedin.com/in/khuedoan"
  showReadingTime: true
  showToc: true

outputs:
  home:
    - HTML
    - JSON
    - RSS

menu:
  main:
    - name: Search
      url: /search/
      weight: 1
    - name: Archives
      url: /archives/
      weight: 2
    - name: About
      url: /about/
      weight: 3

enableEmoji: true
