steps:
  docker-build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: registry.khuedoan.com/blog
      cache_from: registry.khuedoan.com/docker-build-cache
      cache_to: registry.khuedoan.com/docker-build-cache
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: push
