name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: node-modules
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-

    - name: Setup Node.js
      uses: actions/setup-node@v1

    - name: Install modules
      run: npm install

    - name: Test
      run: npm run test

    - name: Build
      run: npm run build

    - name: Deploy
      run: |
        git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/khuedoan/khuedoan.com.git
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        npm run deploy
