name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Node.js
      uses: actions/setup-node@v1
    - name: Install modules
      run: npm install
    - name: Test
      run: npm run test
    - name: Build
      run: npm run build
    - name: Deploy
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        npm run deploy
